#define PRE_END_OF_FILE                  1
#define PRE_COMMENT_START                2
#define PRE_COMMENT_END                  3
#define PRE_VARIABLE_TYPE_VARCHAR        4
#define PRE_SEMICOLON                    5
#define PRE_VARIABLE_TYPE_BOOL           6
#define PRE_VARIABLE_TYPE_NUMBER         7
#define PRE_VARIABLE_TYPE_DATE           8
#define PRE_VARIABLE_TYPE_REDIS          9
#define PRE_VARIABLE_TYPE_VOID          10
#define PRE_FUNCTION_BEGIN              11
#define PRE_FUNCTION_END                12
#define PRE_FUNCTION_BODY_LINE          13
#define PRE_IDENTIFIER                  14
#define PRE_OPEN_PARAN                  15
#define PRE_CLOSE_PARAN                 16
#define PRE_COMMA                       17
