#define END_OF_FILE                      1
#define TAG_DOCTYPE_HTSQL_DTD            2
#define TAG_DOCTYPE_HTML                 3
#define TAG_TREE_OPEN                    4
#define TAG_TREE_BLOCK_CLOSE             5
#define PROPERTYDATA                     6
#define SPACE                            7
#define PROP_TREE_NAME                   8
#define ASSIGMENT                        9
#define TAG_DATALIST_OPEN               10
#define TAG_DATALIST_BLOCK_CLOSE        11
#define PROP_DATALIST_DATALIST_NAME     12
#define PROP_DATALIST_CONNECTION_NAME   13
#define TAG_CONTROLBLOCK_OPEN           14
#define TAG_CONTROLBLOCK_CLOSE          15
#define PROP_CONTROLBLOCK_BLOCK_NAME    16
#define PROPERTYID                      17
#define TAG_DATABLOCK_OPEN              18
#define TAG_DATABLOCK_BLOCK_CLOSE       19
#define PROP_BLOCK_JOIN_CONDITION       20
#define PROP_BLOCK_CONNECTION_NAME      21
#define PROP_BLOCK_AUTO_GENERATED_COLUMNS  22
#define PROP_BLOCK_RECORD_COUNT         23
#define PROP_BLOCK_DATA_SOURCE_NAME     24
#define PROP_BLOCK_DATA_SCHEMA_NAME     25
#define PROP_BLOCK_BLOCK_NAME           26
#define PROP_BLOCK_KEY_COLUMN_NAME      27
#define PROP_BLOCK_MASTER_BLOCK_NAME    28
#define PROP_BLOCK_INSERT_ALLOWED       29
#define PROP_BLOCK_DELETE_ALLOWED       30
#define PROP_BLOCK_UPDATE_ALLOWED       31
#define PROP_BLOCK_WHERE_CLAUSE         32
#define PROP_BLOCK_OREDERBY_CLAUSE      33
#define TAG_SHORT_CLOSE                 34
#define TAG_INPUT_OPEN                  35
#define TAG_SELECT_OPEN                 36
#define TAG_TEXTAREA_OPEN               37
#define TAG_INPUT_BLOCK_CLOSE           38
#define TAG_SELECT_BLOCK_CLOSE          39
#define TAG_TEXTAREA_BLOCK_CLOSE        40
#define PROP_INPUT_CHECKED_VALUE        41
#define PROP_INPUT_UNCHECKED_VALUE      42
#define PROP_INPUT_NAME                 43
#define PROP_INPUT_SEQUENCE_NAME        44
#define PROP_INPUT_SEQUENCE_SCHEMA_NAME  45
#define PROP_INPUT_MASTER_ITEM_NAME     46
#define PROP_INPUT_TYPE                 47
#define PROP_INPUT_VALUE                48
#define PROP_INPUT_DEFAULT_VALUE        49
#define PROP_INPUT_COLUMN_NAME          50
#define PROP_INPUT_FORMAT_MASK          51
#define PROP_INPUT_DATA_TYPE            52
#define PROP_INPUT_MAX_LENGTH           53
#define PROP_INPUT_INSERT_ALLOWED       54
#define PROP_INPUT_UPDATE_ALLOWED       55
#define PROP_INPUT_DATALIST_NAME        56
#define PROP_INPUT_LOOKUP_ITEM_NAME     57
#define PROP_INPUT_LOOKUP_ITEM_BLOCK_NAME  58
#define TAG_TABLE_OPEN                  59
#define TAG_TABLE_BLOCK_CLOSE           60
#define TAG_THEAD_OPEN                  61
#define TAG_THEAD_BLOCK_CLOSE           62
#define TAG_TFOOT_OPEN                  63
#define TAG_TFOOT_BLOCK_CLOSE           64
#define TAG_TBODY_OPEN                  65
#define TAG_TBODY_BLOCK_CLOSE           66
#define TAG_TR_OPEN                     67
#define TAG_TR_BLOCK_CLOSE              68
#define TAG_TD_OPEN                     69
#define TAG_TD_BLOCK_CLOSE              70
#define TAG_TH_OPEN                     71
#define TAG_TH_BLOCK_CLOSE              72
#define TAG_TITLE_OPEN                  73
#define TAG_TITLE_BLOCK_CLOSE           74
#define TAG_LINK_OPEN                   75
#define TAG_LINK_BLOCK_CLOSE            76
#define TAG_META_OPEN                   77
#define TAG_META_BLOCK_CLOSE            78
#define TAG_STYLE_OPEN                  79
#define TAG_STYLE_BLOCK_CLOSE           80
#define PROPERTYID_SCRIPT_SRC           81
#define PROPERTYID_SCRIPT_TYPE          82
#define TAG_SCRIPT_OPEN                 83
#define TAG_SCRIPT_BLOCK_CLOSE          84
#define TAG_HTML_OPEN                   85
#define TAG_HTML_BLOCK_CLOSE            86
#define TAG_BODY_OPEN                   87
#define TAG_BODY_BLOCK_CLOSE            88
#define TAG_HEAD_OPEN                   89
#define TAG_HEAD_BLOCK_CLOSE            90
#define TAG_CLOSE                       91
#define HTMLTEXT                        92
#define ENTER                           93
